---
- name: Create libwizard database secret for python_jobs
  community.docker.docker_secret:
    name: "{{ item.prefix ~ metridoc_secrets_version }}"
    data: '{{ lookup("template", item.template) }}'
    state: present
  no_log: true
  loop:
    - prefix: "metridoc_python_jobs_libwizard_secret_v"
      template: "libwizard.ini.j2"
    - prefix: "metridoc_python_jobs_database_secret_v"
      template: "metridoc.ini.j2"

- name: Deploy python jobs
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
