SELECT
  'A' || id AS id,
  response_id,
  submitted,
  consultation_or_instruction,
  staff_pennkey,
  additional_staff_pennkey,
  division,
  department_csc,
  department_ope,
  department_tdi,
  departmental_library,
  staff_expertise,
  event_date,
  mode_of_consultation,
  rtg,
  session_type,
  service_provided,
  service_space_or_information,
  physical_or_electronic,
  outcome,
  research_community,
  number_of_registrations,
  total_attendance,
  location,
  event_length,
  prep_time,
  number_of_interactions,
  patron_type,
  undergraduate_student_type,
  graduate_student_type,
  mba_type,
  campus,
  patron_name,
  school_affiliation,
  graduation_year,
  academic_department,
  faculty_sponsor,
  course_sponsor,
  course_name,
  course_number,
  patron_question,
  session_description,
  notes,
  downloaded_at,
  upload_record,
  NULL AS referral_method,
  false AS returning_user
FROM ss_libwizard_candi_autos

UNION

SELECT
  'M' || id AS id,
  NULL AS response_id,
  NULL AS submitted,
  consultation_or_instruction,
  staff_pennkey,
  additional_staff_pennkey,
  division,
  department_csc,
  department_ope,
  department_tdi,
  departmental_library,
  staff_expertise,
  event_date,
  mode_of_consultation,
  rtg,
  session_type,
  service_provided,
  service_space_or_information,
  physical_or_electronic,
  outcome,
  research_community,
  number_of_registrations,
  total_attendance,
  location,
  event_length,
  prep_time,
  number_of_interactions,
  patron_type,
  undergraduate_student_type,
  graduate_student_type,
  mba_type,
  campus,
  patron_name,
  school_affiliation,
  graduation_year,
  academic_department,
  faculty_sponsor,
  course_sponsor,
  course_name,
  course_number,
  patron_question,
  session_description,
  notes,
  NULL AS downloaded_at,
  upload_record,
  NULL AS referral_method,
  false AS returning_user
FROM ss_libwizard_candi_manuals

UNION

SELECT
  'L' || id AS id,
  NULL AS response_id,
  submitted,
  consultation_or_instruction,
  staff_pennkey,
  additional_staff_pennkey,
  NULL AS division,
  NULL AS department_csc,
  NULL AS department_ope,
  NULL AS department_tdi,
  NULL AS departmental_library,
  staff_expertise,
  event_date,
  mode_of_consultation,
  rtg,
  session_type,
  service_provided,
  NULL AS service_space_or_information,
  NULL AS physical_or_electronic,
  outcome,
  research_community,
  number_of_registrations,
  total_attendance,
  location,
  event_length,
  prep_time,
  number_of_interactions,
  patron_type,
  undergraduate_student_type,
  graduate_student_type,
  mba_type,
  campus,
  patron_name,
  school_affiliation,
  graduation_year,
  department AS  academic_department,
  faculty_sponsor,
  course_sponsor,
  course_name,
  course_number,
  patron_question,
  session_description,
  notes,
  NULL AS downloaded_at,
  upload_record,
  referral_method,
  returning_user
FROM ss_libwizard_candi_legacies