---
- name: Create docker secrets for rails configs
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: '{{ lookup("ansible.builtin.template", item.file) }}'
    rolling_versions: true
    state: present
  register: metridoc_config_secrets
  loop: "{{ metridoc_configs }}"
  no_log: true

- name: Create custom docker image
  community.docker.docker_image:
    build:
      dockerfile: Dockerfile
      path: /metridoc
      pull: true
      target: development
    force_tag: true
    force_source: true
    name: "{{ metridoc_image_name }}:{{ metridoc_image_tag }}"
    source: build
    state: present
  when: is_development | default(false, true)

- name: Deploy metridoc app
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
