---
- name: create nfs volume for /home/app/webapp/tmp
  docker_volume:
    name: metridoc_tmp_data_dist
    driver: local
    driver_options:
      type: nfs
      o: "{{ 'addr=' ~ nfs_metridoc_tmp_address ~ ',rw' }}"
      device: ":{{ nfs_metridoc_tmp_device }}"
    state: present
  tags: nfs_mount
  when: not is_development

- name: create nfs volume for /home/app/webapp/tmp for development
  docker_volume:
    name: metridoc_tmp_data_dist
    state: present
  tags: nfs_mount
  when: is_development


- name: create metridoc config directory
  file:
    path: "{{ config_dir }}/metridoc"
    mode: 0440
    state: directory

- name: copy docker compose file
  copy:
    src: docker-compose.yml
    dest: "{{ config_dir }}/metridoc/docker-compose.yml"
    mode: 0440

- name: label metridoc swarm node
  docker_node:
    hostname: "{{ metridoc_swarm_node }}"
    labels:
      metridoc: "true"
  tags:
    - docker

# - name: check template lookup
  # debug: msg=metridoc_rails_{{ item }}_config_{{ lookup('vars', 'rails_' + item + '_config_version') }}
  # loop:
    # - database
    # - secrets

- name: create docker secrets for rails configs
  docker_secret:
    name: metridoc_rails_{{ item }}_config_{{ lookup('vars', 'rails_' + item + '_config_version') }}
    data: '{{ lookup("template", item + ".yml.j2") }}'
    state: present
  loop:
    - database
    - secrets
  no_log: false
  tags:
    - docker

# Build the docker image
- name: Build docker image
  import_tasks: ./build_docker_image.yml
  when: is_development
  tags: dev_environment

- name: start docker services
  environment: "{{ docker_stack_env }}"
  command: docker stack deploy -c {{ config_dir }}/metridoc/docker-compose.yml metridoc
  changed_when: false
  tags:
    - docker
