---
- name: create nfs volume for /home/app/webapp/tmp
  docker_volume:
    name: metridoc_tmp_data_dist
    driver: local
    driver_options:
      type: nfs
      o: "{{ 'addr=' ~ nfs_metridoc_tmp_address ~ ',rw' }}"
      device: ":{{ nfs_metridoc_tmp_device }}"
    state: present
  tags: nfs_mount

- name: create nfs volume for gate_count
  docker_volume:
    name: gate_count
    driver: local
    driver_options:
      type: nfs
      o: "{{ 'addr=' ~ ezpaarse_nfs_input_volume_address ~ ',rw' }}"
      device: ":{{ ezpaarse_nfs_input_volume_device }}"
    state: present
  tags: nfs_mount

- name: create metridoc config directory
  file:
    path: "{{ config_dir }}/metridoc"
    mode: 0440
    state: directory

- name: copy docker compose file
  copy:
    src: docker-compose.yml
    dest: "{{ config_dir }}/metridoc/docker-compose.yml"
    mode: 0440

- name: label metridoc swarm node
  docker_node:
    hostname: "{{ metridoc_swarm_node }}"
    labels:
      metridoc: "true"
  tags:
    - docker

- name: create docker secrets for rails configs
  docker_secret:
    name: metridoc_rails_{{ item }}_config_{{ lookup('vars', 'rails_' + item + '_config_version') }}
    data: '{{ lookup("template", item + ".yml.j2") }}'
    state: present
  loop:
    - database
    - secrets
  no_log: true
  tags:
    - docker

- name: start docker services
  environment: "{{ docker_stack_env }}"
  command: docker stack deploy -c {{ config_dir }}/metridoc/docker-compose.yml metridoc
  changed_when: false
  tags:
    - docker
