---
- name: Create custom docker image
  community.docker.docker_image_build:
    name: "{{ metridoc_image_name }}"
    tag: "{{ metridoc_image_tag }}"
    path: "/metridoc"
    dockerfile: "Dockerfile"
    target: "development"
    args:
      RAILS_ENV: "{{ rails_env }}"
  when: is_development | default(false, true)

- name: Create docker secrets
  community.docker.docker_secret:
    name: "{{ 'metridoc_rails_master_key_v' ~ metridoc_vault_values.metadata.version }}"
    data: "{{ rails_master_key }}"
    state: present
  no_log: true

- name: Deploy metridoc app
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
