---
include:
  - component: gitlab.library.upenn.edu/devops/gitlab/components/deploy/deploy@~latest
    inputs:
      deploy_environment_url: "https://metridoc-staging.library.upenn.edu"
      valid_principals: "${VALID_PRINCIPALS}"
      vault_auth_role: "${VAULT_AUTH_ROLE}"
      vault_ssh_client_role: "${VAULT_SSH_CLIENT_ROLE}"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/deploy/deploy@~latest
    inputs:
      deploy_environment: "production"
      deploy_environment_url: "https://metridoc.library.upenn.edu"
      job_suffix: "production"
      valid_principals: "${VALID_PRINCIPALS}"
      vault_auth_role: "${VAULT_AUTH_ROLE}"
      vault_ssh_client_role: "${VAULT_SSH_CLIENT_ROLE}"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      stage: "build_base"
      docker_target: "base"
      job_suffix: "_base"
      docker_additional_cache_targets: "base"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      stage: "build_development"
      docker_target: "development"
      job_suffix: "_development"
      docker_additional_cache_targets: "base development"
      needs_build:
        - "amend_manifest_base"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_build@~latest
    inputs:
      stage: "build_production"
      docker_additional_cache_targets: "base development production"
      docker_target: "production"
      job_suffix: "_production"
      docker_build_args: "--build-arg RAILS_ENV=production"
      needs_build: 
        - "amend_manifest_development"
  - component: $CI_SERVER_FQDN/devops/gitlab/components/sast/trivy@~latest
    inputs:
      docker_tag_to_scan: "${CI_COMMIT_SHA}"
      job_image_tag: "29-dind"
      needs:
        - "amend_manifest_production"
      stage: "test"
  - component: gitlab.library.upenn.edu/devops/gitlab/components/docker/stage_finalize@~latest
    inputs:
      needs_copy:
        - trivy_scan
 


stages:
  - build_base
  - build_development
  - build_production
  - test
  - finalize
  - deploy

# Deploy staging
deploy_staging:
  rules:
    - if: $CI_COMMIT_REF_NAME == "staging"
  tags:
    - deploy 

# Deploy production
deploy_production:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  tags:
    - deploy
