INSERT INTO sceti_trackings(
    sceti_project_id,
    date_received_in_sceti,
    date_returned,
    deadline,
    remove_from_project,
    mms,
    ark,
    images,
    pages_to_digitize,
    file_location,
    title,
    patron_name,
    condition_notes,
    general_notes,
    qa,
    imaged_by,
    imaged_date,
    uploaded_to_colenda_by,
    uploaded_to_colenda_date,
    qa_by,
    qa_date,
    metadata_created_by,
    metadata_created_date,
    web_qa_by,
    web_qa_date
)
SELECT 
    P.id AS sceti_project_id,
    S.SentSCETI AS date_received_in_sceti,
    S.ReturnedSCETI AS date_returned,
    S.Deadline AS deadline,
    S.RemovedProject AS remove_from_project,
    S.CallNumMSSNum AS mms,
    null AS ark,
    S.TotalNumImages AS images,
    S.PagesToDig AS pages_to_digitize,
    S.StorageFolder AS file_location,
    null AS title,
    S.PatronName AS patron_name,
    S.ConditionNotes AS condition_notes,
    S.NotesInstructions AS general_notes,
    S.QAPass AS qa,
    S.ImagingBy AS imaged_by,
    S.ImagingComplete AS imaged_date,
    null AS uploaded_to_colenda_by,
    null AS uploaded_to_colenda_date,
    null AS qa_by,
    null AS qa_date,
    S.MetadataBy AS metadata_created_by,
    S.MetadataComplete AS metadata_created_date,
    null AS web_qa_by,
    null AS web_qa_date
FROM scetisample S LEFT OUTER JOIN sceti_projects P ON S.Project=P.Name
