version: "3.7"

# Default logging
x-logging: &default-logging
  driver: json-file
  options:
    max-file: "3"
    max-size: "10m"

services:
  alertmanager-1:
    image: prom/alertmanager:v0.17.0
    command: >
      --cluster.peer=alertmanager-2:9094
      --config.file=/etc/alertmanager/alertmanager.yml
      --storage.path=/alertmanager
      --web.external-url=${ALERTMANAGER_1_EXTERNAL_URL}
    configs:
      - source: alertmanager_templates
        target: /etc/alertmanager/template/templates.tmpl
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.alertmanager-1 == true
      replicas: 1
    logging: *default-logging
    networks:
      - monitoring
    ports:
      - "9093:9093"
    secrets:
      - source: alertmanager_config
        target: /etc/alertmanager/template/alertmanager.yml
    volumes:
      - alertmanager_1_data:/alertmanager

  alertmanager-2:
    image: prom/alertmanager:v0.17.0
    command: >
      --cluster.peer=alertmanager-1:9094
      --config.file=/etc/alertmanager/alertmanager.yml
      --storage.path=/alertmanager
      --web.external-url=${ALERTMANAGER_2_EXTERNAL_URL}
    configs:
      - source: alertmanager_templates
        target: /etc/alertmanager/templates.tmpl
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.alertmanager-2 == true
      replicas: 1
    logging: *default-logging
    networks:
      - monitoring
    ports:
      - "9094:9093"
    secrets:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
    volumes:
      - alertmanager_2_data:/alertmanager

  grafana:
    image: grafana/grafana:6.2.1
    configs:
      - source: grafana_dashboards
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: grafana_dashboard_postgres
        target: /etc/grafana/provisioning/dashboards/postgres.json
      - source: grafana_dashboard_home
        target: /etc/grafana/provisioning/dashboards/home.json
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana-db
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD__FILE: /run/secrets/grafana_database_password
      GF_DATABASE_SSL_MODE: disable
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_SERVER_ROOT_URL:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_FROM_ADDRESS: grafana@metridoc.library.upenn.edu
      GF_SMTP_HOST:
    logging: *default-logging
    networks:
      - monitoring
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_password
      - grafana_database_password
    volumes:
      - grafana_data:/var/lib/grafana

  grafana-db:
    image: postgres:11.3-alpine
    command: >
      postgres
        -c hba_file=/var/lib/postgresql/pg_hba.conf
    configs:
      - source: grafana_database_pg_hba_conf
        target: /var/lib/postgresql/pg_hba.conf
        uid: "70"
        gid: "70"
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.postgres-primary == true
      replicas: 1
    environment:
      POSTGRES_DB: grafana
      POSTGRES_PASSWORD_FILE: /run/secrets/grafana_database_password
      POSTGRES_USER: grafana
    logging: *default-logging
    networks:
      - monitoring
    secrets:
      - grafana_database_password
    volumes:
      - grafana_db_data:/var/lib/postgresql/data

  node-exporter:
    image: prom/node-exporter:v0.18.0
    command: >
      --collector.textfile.directory=/home
      --path.procfs=/host/proc
      --path.rootfs=/rootfs
      --path.sysfs=/host/sys
    configs:
      - source: node_exporter_entrypoint
        target: /home/docker-entrypoint.sh
        mode: 0555
    deploy:
      mode: global
    entrypoint: /home/docker-entrypoint.sh
    environment:
      NODE_ID: "{{.Node.ID}}"
      NODE_NAME: "{{.Node.Hostname}}"
    logging: *default-logging
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  prometheus:
    image: prom/prometheus:v2.10.0
    configs:
      - source: prometheus_alerts
        target: /etc/prometheus/rules/alerts.yml
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: ${PROMETHEUS_REPLICAS}
    logging: *default-logging
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.4.7
    configs:
      - source: postgres_exporter_queries
        target: /queries.yml
    environment:
      DATA_SOURCE_PASS_FILE: /run/secrets/postgres_monitoring_password
      DATA_SOURCE_USER: monitoring
      DATA_SOURCE_URI: primary-db:5432/postgres?sslmode=disable
      PG_EXPORTER_EXTEND_QUERY_PATH: /queries.yml
    logging: *default-logging
    networks:
      - database
      - monitoring
    secrets:
      - postgres_monitoring_password

configs:
  alertmanager_templates:
    file: alertmanager/templates.tmpl
    name: metridoc_alertmanager_templates_${ALERTMANAGER_TEMPLATES_VERSION}
  grafana_dashboards:
    file: grafana/dashboards.yml
    name: metridoc_grafana_dashboards_${GRAFANA_DASHBOARDS_VERSION}
  grafana_dashboard_home:
    file: grafana/dashboard_home.json
    name: metridoc_grafana_dashboard_home_${GRAFANA_DASHBOARD_HOME_VERSION}
  grafana_dashboard_postgres:
    file: grafana/dashboard_postgres.json
    name: metridoc_grafana_dashboard_postgres_${GRAFANA_DASHBOARD_POSTGRES_VERSION}
  grafana_datasources:
    file: grafana/datasources.yml
    name: metridoc_grafana_datasources_${GRAFANA_DATASOURCES_VERSION}
  grafana_database_pg_hba_conf:
    file: grafana_db/pg_hba.conf
    name: metridoc_grafana_database_pg_hba_conf_${GRAFANA_DATABASE_PG_HBA_CONF_VERSION}
  node_exporter_entrypoint:
    file: node_exporter/docker-entrypoint.sh
    name: metridoc_node_exporter_entrypoint_${NODE_EXPORTER_ENTRYPOINT_VERSION}
  postgres_exporter_queries:
    file: postgres_exporter/queries.yml
    name: metridoc_postgres_exporter_queries_${POSTGRES_EXPORTER_QUERIES_VERSION}
  prometheus_alerts:
    file: prometheus/alerts.yml
    name: metridoc_prometheus_alerts_${PROMETHEUS_ALERTS_VERSION}
  prometheus_config:
    file: prometheus/prometheus.yml
    name: metridoc_prometheus_config_${PROMETHEUS_CONFIG_VERSION}

networks:
  database:
    external: true
  monitoring:
    driver: overlay
    ipam:
      config:
        - subnet: ${MONITORING_SUBNET}

secrets:
  alertmanager_config:
    external: true
    name: metridoc_alertmanager_config_${ALERTMANAGER_CONFIG_VERSION}
  grafana_admin_password:
    external: true
    name: metridoc_grafana_admin_password_${GRAFANA_ADMIN_PASSWORD_VERSION}
  grafana_database_password:
    external: true
    name: metridoc_grafana_database_password_${GRAFANA_DATABASE_PASSWORD_VERSION}
  postgres_monitoring_password:
    external: true
    name: metridoc_postgres_monitoring_password_${POSTGRES_MONITORING_PASSWORD_VERSION}

volumes:
  alertmanager_1_data:
  alertmanager_2_data:
  grafana_data:
  grafana_db_data:
  prometheus_data:
