---
- name: Create ezpaarse docker secrets
  community.docker.docker_secret:
    name: metridoc_{{ item }}_{{ metridoc_secrets_version }}
    data: '{{ lookup("vars", item) }}'
    state: present
  loop:
    - ezpaarse_mongodb_password
    - ezpaarse_mongodb_username
    - ezpaarse_mongodb_root_password
    - ezpaarse_mongodb_root_username
  no_log: true

- name: Create docker config secret for ezpaarse
  community.docker.docker_secret:
    name: "metridoc_ezpaarse_config"
    data: "{{ lookup('template', 'config.local.json.j2') | to_json }}"
    rolling_versions: true
    state: present
  register: ezpaarse_config
  no_log: true

- name: debug
  debug:
    var: ezpaarse_config

- name: Deploy ezpaarse
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  # no_log: true
