ActiveAdmin.register UpennEzproxy::EzpaarseJob do
  menu if: proc{ authorized?(:read, "UpennEzproxy") },
   label: I18n.t("active_admin.ezproxy.ezproxy_menu"),
   parent: I18n.t("active_admin.resource_sharing")
   
  permit_params :datetime,
   :login,
   :platform,
   :platform_name,
   :rtype,
   :mime,
   :print_identifier,
   :online_identifier,
   :title_id,
   :doi,
   :publication,
   :publication_date,
   :unitid,
   :domain,
   :on_campus,
   :log_id,
   :geoip_country,
   :geoip_region,
   :geoip_city,
   :geoip_latitude,
   :geoip_longitude,
   :host,
   :method,
   :url,
   :status,
   :size,
   :referer,
   :session_id,
   :resource_name
end
