---
collections:
  - name: community.crypto

roles:
  - name: atosatto.docker-swarm
    src: https://gitlab.library.upenn.edu/devops/ansible/ansible-dockerswarm.git
    scm: git
    version: master
  - name: nginxinc.nginx
  - name: nginxinc.nginx_config
  - name: shibboleth_sp
    src: https://github.com/upenn-libraries/ansible_shibboleth_sp.git
    scm: git
