version: "3.7"

# Default logging
x-logging: &default-logging
  driver: json-file
  options:
    max-file: "3"
    max-size: "10m"

services:
  ezpaarse:
    image: quay.io/upennlibraries/metridoc-ezpaarse:${EZPAARSE_IMAGE_TAG}
    environment:
      NODE_ENV: "production"
    deploy:
      placement:
        constraints:
          - node.labels.metridoc == true
    logging: *default-logging
    networks:
      - database
      - ezpaarse
    volumes:
      - ezpaarse_platforms:/opt/ezpaarse/platforms
      - ezpaarse_middlewares:/opt/ezpaarse/middlewares
      - ezpaarse_resources:/opt/ezpaarse/resources
      - ezpaarse_exclusions:/opt/ezpaarse/exclusions
      - ezpaarse_input_dist:/tmp/ezpaarse_input
      - ezpaarse_output:/tmp/ezpaarse_output
    secrets:
      - source: metridoc_ezpaarse_config
        target: /opt/ezpaarse/config.local.json
        uid: "1000"
        gid: "1000"
        mode: 0440
      - postgres_database_password
    restart: unless-stopped

  ezpaarse_db:
    image: quay.io/upennlibraries/metridoc-ezpaarse-mongodb:${EZPAARSE_MONGODB_IMAGE_TAG}
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/metridoc_ezpaarse_mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/metridoc_ezpaarse_mongodb_root_username
      MONGO_INITDB_DATABASE: ezpaarse
      MONGO_USERNAME_FILE: /run/secrets/metridoc_ezpaarse_mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/metridoc_ezpaarse_mongodb_password
    logging: *default-logging
    networks:
      - ezpaarse
    restart: unless-stopped
    secrets:
      - metridoc_ezpaarse_mongodb_root_password
      - metridoc_ezpaarse_mongodb_root_username
      - metridoc_ezpaarse_mongodb_password
      - metridoc_ezpaarse_mongodb_username

networks:
  database:
    driver: overlay
    ipam:
      config:
        - subnet: ${DATABASE_SUBNET}
  ezpaarse:
    driver: overlay

secrets:
  metridoc_ezpaarse_config:
    external: true
    name: metridoc_ezpaarse_config_${EZPAARSE_CONFIG_VERSION}
  metridoc_ezpaarse_mongodb_root_password:
    external: true
    name: metridoc_ezpaarse_mongodb_root_password_${EZPAARSE_MONGODB_ROOT_PASSWORD_VERSION}
  metridoc_ezpaarse_mongodb_root_username:
    external: true
    name: metridoc_ezpaarse_mongodb_root_username_${EZPAARSE_MONGODB_ROOT_USERNAME_VERSION}
  metridoc_ezpaarse_mongodb_password:
    external: true
    name: metridoc_ezpaarse_mongodb_password_${EZPAARSE_MONGODB_PASSWORD_VERSION}
  metridoc_ezpaarse_mongodb_username:
    external: true
    name: metridoc_ezpaarse_mongodb_username_${EZPAARSE_MONGODB_USERNAME_VERSION}
  postgres_database_password:
    external: true
    name: metridoc_postgres_database_password_${POSTGRES_DATABASE_PASSWORD_VERSION}

volumes:
  ezpaarse_exclusions:
  ezpaarse_input_dist:
    external: true
  ezpaarse_middlewares:
  ezpaarse_output:
    external: true
  ezpaarse_platforms:
  ezpaarse_resources:
