---
- name: Create template configs
  community.docker.docker_config:
    name: "metridoc_postgres_primary_pg_hba_conf"
    data: "{{ lookup('template', 'pg_hba.conf.j2') }}"
    rolling_versions: true
    state: present
  register: primary_postgres_pg_hba_conf_config
  no_log: true

- name: Create docker secret for init_primary query
  community.docker.docker_secret:
    name: metridoc_postgres_init_primary
    data: '{{ lookup("template", "init_primary.sql.j2") }}'
    rolling_versions: true
    state: present
  register: primary_postgres_init_primary_secret
  no_log: true

- name: Create docker secret for database password
  community.docker.docker_secret:
    name: metridoc_postgres_database_password_{{ metridoc_secrets_version }}
    data: "{{ postgres_database_password }}"
    state: present
  no_log: true

- name: Deploy postgres
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
