---
load_sequence: 1
target_model: "Ezproxy::EzpaarseLog"
target_adapter: "csv"
truncate_before_load: "no"
file_name: "ezpaarse_out.csv"

checksum_index:
  - login
  - session_id
  - url
  - referer
  - size

unique_keys:
  - datetime
  - checksum_index
upsert: true
