version: '3.7'

# Default logging
x-logging:
  &default-logging
  driver: json-file
  options:
    max-file: '3'
    max-size: '10m'

services:
  jenkins:
    image: gitlab.library.upenn.edu/metridoc1/metridoc_jenkins/metridoc_jenkins:${JENKINS_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.jenkins == true
    entrypoint: ./docker-entrypoint.sh
    logging: *default-logging
    networks:
      - jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    driver: overlay

volumes:
  jenkins_home:
