default: &default
  pool: 8
  adapter: postgresql
  database: postgres
  username: postgres
  password: <%= DockerSecrets.lookup(:postgres_database_password, ENV['DATABASE_PASSWORD']) %>
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100

development:
  host: primary-db
  <<: *default

test:
  host: primary-db
  <<: *default

staging:
  primary:
    host: primary-db
    <<: *default

  primary_replica:
    host: replica-db
    replica: true
    <<: *default

production:
  primary:
    host: primary-db
    <<: *default

  primary_replica:
    host: replica-db
    replica: true
    <<: *default