default: &default
  pool: 8
  adapter: postgresql
  database: postgres
  username: postgres
  password: <%= DockerSecrets.lookup(:postgres_database_password, ENV['DATABASE_PASSWORD']) %>
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100

development:
  <<: *default
  host: "<%= ENV['LOCAL_METRIDOC_DATABASE'].present? ? 'localhost' : 'primary-db' %>"
  adapter: postgresql
  database: "<%= ENV.fetch('LOCAL_METRIDOC_DATABASE', 'postgres') %>"
  username: "<%= ENV.fetch('LOCAL_METRIDOC_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('LOCAL_METRIDOC_PASSWORD', DockerSecrets.lookup(:postgres_database_password, ENV['DATABASE_PASSWORD'])) %>"

test:
  <<: *default
  host: "<%= ENV['LOCAL_TEST_METRIDOC_DATABASE'].present? ? 'localhost' : 'primary-db' %>"
  adapter: postgresql
  database: "<%= ENV.fetch('LOCAL_TEST_METRIDOC_DATABASE', 'postgres') %>"
  username: "<%= ENV.fetch('LOCAL_TEST_METRIDOC_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('LOCAL_TEST_METRIDOC_PASSWORD', DockerSecrets.lookup(:postgres_database_password, ENV['DATABASE_PASSWORD'])) %>"


staging:
  primary:
    host: primary-db
    <<: *default

  primary_replica:
    host: replica-db
    replica: true
    <<: *default

production:
  primary:
    host: primary-db
    <<: *default

  primary_replica:
    host: replica-db
    replica: true
    <<: *default