---
nginx_config_debug_output: true
nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    backup: true
    config:
      servers:
        - core:
            server_name: "metridoc-dev.library.upenn.edu"
            listen:
              - port: 443
                ip: 0.0.0.0
                ssl: true
          locations:
            - location: /
              proxy:
                address: 0.0.0.0
                pass: "http://127.0.0.1"
                pass_request_headers: true
                set_header:
                  - field: Host
                    value: $host
                  - field: X-Real-IP
                    value: $remote_addr
                  - field: X-Forwarded-For
                    value: $proxy_add_x_forwarded_for
                  - field: X-Forwarded-Host
                    value: $host
                  - field: X-Forwarded-Server
                    value: $host
                  - field: X-Forwarded-Proto
                    value: $scheme
                  - field: X-Forwarded-Ssl
                    value: on
                  - field: X-Forwarded-Port
                    value: $server_port
          ssl:
            certificate: "/etc/ssl/proxy.crt"
            certificate_key: "/etc/ssl/proxy.key"
