---
shibboleth:
  image:
    name: "shibboleth_dev"
    tag: "latest"
  is_development: true
  swarm_node_constraint: "metridoc"
  templates:
    configs:
      shib2:
        path: "shibboleth/apache/shib2.conf.j2"
        values:
          admin_email: "{{ metridoc_vault_values.secret.shib2_admin_email }}"
          fqdn: "{{ metridoc_vault_values.secret.shib2_fqdn }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
    secrets:
      attribute_map:
        path: "shibboleth/shibboleth/attribute_map.xml.j2"
        version: "{{ metridoc_vault_values.metadata.version }}"
      metadata:
        path: "shibboleth/metadata.xml.j2"
        value: "{{ metridoc_vault_values.secret.metadata_value }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
      shibboleth2:
        path: "shibboleth/shibboleth2.xml.j2"
        values:
          sp_entityID: "{{ metridoc_vault_values.secret.shibboleth2_sp_entityID }}"
          idp_entityID: "{{ metridoc_vault_values.secret.shibboleth2_idp_entityID }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
      sp_encrypt_cert:
        path: "shibboleth/sp_encrypt_cert.pem.j2"
        values:
          sp_cert_pem: "{{ metridoc_vault_values.secret.sp_encrypt_cert_pem }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
      sp_encrypt_key:
        path: "shibboleth/sp_encrypt_key.pem.j2"
        values:
          sp_key_pem: "{{ metridoc_vault_values.secret.sp_encrypt_key_pem }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
      sp_signing_cert:
        path: "shibboleth/sp_signing_cert.pem.j2"
        values:
          sp_cert_pem: "{{ metridoc_vault_values.secret.sp_signing_cert_pem }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
      sp_signing_key:
        path: "shibboleth/sp_signing_key.pem.j2"
        values:
          sp_key_pem: "{{ metridoc_vault_values.secret.sp_signing_key_pem }}"
        version: "{{ metridoc_vault_values.metadata.version }}"
