---
- name: Create configs
  community.docker.docker_config:
    name: "{{ item.name }}"
    data: "{{ lookup(item.type, item.file) }}"
    rolling_versions: true
    state: present
  no_log: true
  register: replica_docker_configs
  loop: "{{ replica_configs }}"

- name: Create docker secret for database password
  community.docker.docker_secret:
    name: metridoc_postgres_database_password_v{{ metridoc_secrets_version }}
    data: "{{ postgres_database_password }}"
    state: present
  no_log: true

- name: Create docker secret for .pgpass file
  community.docker.docker_secret:
    name: metridoc_postgres_pgpass_v{{ metridoc_secrets_version }}
    data: '{{ lookup("template", ".pgpass.j2") }}'
    state: present
  no_log: true

- name: Deploy postgres replica
  community.docker.docker_stack:
    name: "metridoc"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
