class AddSsLibwizardCandi < ActiveRecord::Migration[7.1]
  def change
    create_table :ss_libwizard_candi_autos do |t|
      t.string "response_id"
      t.datetime "submitted", precision: nil
      t.string "consultation_or_instruction"
      t.string "staff_pennkey"
      t.string "additional_staff_pennkey"
      t.string "division"
      t.string "department_csc"
      t.string "department_ope"
      t.string "department_tdi"
      t.string "departmental_library"
      t.string "staff_expertise"
      t.date "event_date"
      t.string "mode_of_consultation"
      t.string "rtg"
      t.string "session_type"
      t.string "service_provided"
      t.string "service_space_or_information"
      t.string "physical_or_electronic"
      t.string "outcome"
      t.string "research_community"
      t.integer "number_of_registrations"
      t.integer "total_attendance"
      t.string "location"
      t.integer "event_length"
      t.integer "prep_time"
      t.integer "number_of_interactions"
      t.string "patron_type"
      t.string "undergraduate_student_type"
      t.string "graduate_student_type"
      t.string "mba_type"
      t.string "campus"
      t.string "patron_name"
      t.string "school_affiliation"
      t.integer "graduation_year"
      t.string "academic_department"
      t.string "faculty_sponsor"
      t.string "course_sponsor"
      t.string "course_name"
      t.string "course_number"
      t.string "patron_question"
      t.text "session_description"
      t.text "notes"
      t.datetime "downloaded_at"
      t.boolean "upload_record", default: false
      t.index ["response_id"], unique: true
    end

    create_table :ss_libwizard_candi_manuals do |t|
      t.string "response_id", default: nil
      t.string "consultation_or_instruction"
      t.string "staff_pennkey"
      t.string "additional_staff_pennkey"
      t.string "division"
      t.string "department_csc"
      t.string "department_operations"
      t.string "department_tdi"
      t.string "departmental_library"
      t.string "staff_expertise"
      t.date "event_date"
      t.string "mode_of_consultation"
      t.string "rtg"
      t.string "session_type"
      t.string "service_provided"
      t.string "type_of_access_question"
      t.string "physical_or_electronic_access"
      t.string "outcome"
      t.string "research_community"
      t.integer "number_of_registrations"
      t.integer "total_attendance"
      t.string "location"
      t.integer "event_length"
      t.integer "prep_time"
      t.integer "number_of_interactions"
      t.string "patron_type"
      t.string "undergraduate_student_type"
      t.string "graduate_student_type"
      t.string "mba_type"
      t.string "campus"
      t.string "patron_name"
      t.string "school_affiliation"
      t.integer "graduation_year"
      t.string "academic_department"
      t.string "faculty_sponsor"
      t.string "course_sponsor"
      t.string "course_name"
      t.string "course_number"
      t.string "patron_question"
      t.text "session_description"
      t.text "notes"
      t.boolean "upload_record", default: true
      t.datetime "uploaded_at"
      t.string "filename"
    end

    rename_table :consultation_interactions, :ss_libwizard_candi_legacies

  end
end
