---
load_sequence: 7

target_model: "CourseReserves::Leganto::Course"
target_adapter: "csv"

export_file_name: "course_reserves_courses.csv"

# Flag for the Alma API
source_adapter: "alma"
# URL Encoded report path
report_path: "path=%2Fshared%2FUniversity%20of%20Pennsylvania%2FReports%2FShared%20Reports%2Fmetridoc_reports%2Fleganto%2Fcourse_reserves_courses"
apikey_string: "&apikey="
# Limit must be between 25 and 1000 and a multiple of 25
limit: "&limit=1000"

# API columns to MetriDoc column mapping
# Alma Uses the original column names, not what is assigned in the GUI
# As such, the SQL for any calculations need to be used as column names
column_mappings:
  "Course ID": course_id
  "Course Modification Date": modification_date
  "Course Creation Date": creation_date
  "Course Code": course_code
  "Course Term": course_term
  "Course Year": course_year
  "Academic Department": academic_department
  "Current Course Start Date": course_start_date
  "Current Course End Date": course_end_date
  "Number Of Participants": course_enrollment
  "Course Name": course_name
  "Processing Department": processing_department

# Specify unique keys for the upload
unique_keys: ["course_id"]
upsert: true

# List of specific columns to update on conflict
upsert_columns:
  - "modification_date"
  - "course_enrollment"
  - "course_name"
  - "processing_department"
  - "course_start_date"
  - "course_end_date"
  - "course_code"
  - "course_term"
  - "course_year"

# Filter for request
incremental_filter_sql: '"Courses"."Course Modification Date"'
incremental_filter_column: "modification_date"
