---
load_sequence: 8

target_model: "CourseReserves::Leganto::Citation"
target_adapter: "csv"

export_file_name: "course_reserves_items.csv"

# Flag for the Alma API
source_adapter: "alma"
# URL Encoded report path
report_path: "path=%2Fshared%2FUniversity%20of%20Pennsylvania%2FReports%2FShared%20Reports%2Fmetridoc_reports%2Fleganto%2Fcourse_reserves_citations"
apikey_string: "&apikey="
# Limit must be between 25 and 1000 and a multiple of 25
limit: "&limit=1000"

# API columns to MetriDoc column mapping
# Alma Uses the original column names, not what is assigned in the GUI
# As such, the SQL for any calculations need to be used as column names
column_mappings:
  "Citation Id": citation_id
  "Citation Creation Date (Calendar)": citation_creation_date
  "Citation Created By": citation_created_by
  "Citation Copyright Status": citation_copyright_status
  "Citation Material Type": citation_material_type
  "Citation Origin": citation_origin
  "Citation Source": citation_source
  "Citation Type": citation_type
  "Citation Uploaded File": citation_uploaded_file
  "External Source Id": external_source_id
  "Is Alma Digital Citation": is_alma_digital_citation
  "Is Repository Citation": is_repository_citation
  "Citation Modification Date (Calendar)": citation_modification_date
  "Title": title
  "Author": author
  "Publisher": publisher
  "Publication Date": pub_year
  "Journal Title": journal_title
  "Normalized ISBN": isbn
  "Normalized ISSN": issn
  "Book Chapter Title": book_chapter_title
  "Issue": issue
  "Volume": volume
  "Active Course Code": active_course_code
  "Category of Material": category_of_material
  "Electronic location and access": electronic_location_and_access
  "Form of Item": form_of_item
  "Material Type": material_type
  "Resource Type": resource_type

# Specify unique keys for the upload
unique_keys: ["citation_id"]
upsert: true
# List of specific columns to update on conflict
upsert_columns:
- "citation_copyright_status"
- "citation_material_type"
- "citation_origin"
- "citation_source"
- "citation_type"
- "citation_uploaded_file"
- "external_source_id"
- "is_alma_digital_citation"
- "is_repository_citation"
- "citation_modification_date"
- "title"
- "author"
- "publisher"
- "journal_title"
- "isbn"
- "issn"
- "book_chapter_title"
- "issue"
- "volume"
- "active_course_code"
- "category_of_material"
- "electronic_location_and_access"
- "form_of_item"
- "material_type"
- "resource_type"

# Filter for request
#export_filter_start_date: "2017-07-01"
#export_filter_end_date: "2018-01-01"
