---
load_sequence: 10

target_model: "CourseReserves::Leganto::Usage"
target_adapter: "csv"

export_file_name: "leganto_student_usage.csv"

# Flag for the Alma API
source_adapter: "alma"
# URL Encoded report path
report_path: "path=%2Fshared%2FUniversity%20of%20Pennsylvania%2FReports%2FShared%20Reports%2Fmetridoc_reports%2Fleganto%2Fleganto_student_usage"
apikey_string: "&apikey="
# Limit must be between 25 and 1000 and a multiple of 25
limit: "&limit=1000"

# API columns to MetriDoc column mapping
# Alma Uses the original column names, not what is assigned in the GUI
# As such, the SQL for any calculations need to be used as column names
column_mappings:
  "Course ID": course_id
  "Reading List Id": reading_list_id
  "Citation ID": citation_id
  "Date": event_date
  "User Role": user_role
  "Student Type": student_type
  "Link Type": link_type
  "Number of Citation Views": citation_views
  "Number of Files Downloaded": files_downloaded
  "Number of File Views": file_views
  "Number of Full Text Views": full_text_views

# Specify unique keys for the upload
upsert: true
# List of specific columns to update on conflict
upsert_columns:
  - "citation_views"
  - "files_downloaded"
  - "file_views"
  - "full_text_views"

# Filter for request
incremental_filter_sql: '"Event Date"."Date"'
incremental_filter_column: "event_date"
