---
load_sequence: 11

target_model: "CourseReserves::Leganto::CourseCitation"
target_adapter: "csv"

export_file_name: "course_reserves_course_citations.csv"

# Flag for the Alma API
source_adapter: "alma"
# URL Encoded report path
report_path: "path=%2Fshared%2FUniversity%20of%20Pennsylvania%2FReports%2FShared%20Reports%2Fmetridoc_reports%2Fleganto%2Fcourse_reserves_course_citations"
apikey_string: "&apikey="
# Limit must be between 25 and 1000 and a multiple of 25
limit: "&limit=1000"

# API columns to MetriDoc column mapping
# Alma Uses the original column names, not what is assigned in the GUI
# As such, the SQL for any calculations need to be used as column names
column_mappings:
  "Course ID": course_id
  "Reading List Id": reading_list_id
  "Citation ID": citation_id
  "Citation Modification Date": modification_date

# Filter for request
incremental_filter_sql: '"Reading List Citations"."Citation Modification Date"'
incremental_filter_column: "modification_date"
